In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [25]:
df = pd.read_csv('./3/train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [26]:
df.head(2)

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1

In [27]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [28]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [29]:
X.head(2)

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0

In [30]:
print(X.columns)

Index(['Age', 'Pclass', 'SibSp', 'Parch'], dtype='object')

# Applying Feature Construction

In [31]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [32]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [33]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [34]:
myfunc(4)

1

In [35]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [37]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [38]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [40]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0