In [1]:
import pandas as pd

In [ ]:
df = pd.DataFrame({"name" : ["wscube", "cow", "cat", "dog", "black"]})
df

     name
0  wscube
1     cow
2     cat
3     dog
4   black

In [ ]:
# LabelEncoder import kiya (categorical text data ko numbers me convert karne ke liye)
from sklearn.preprocessing import LabelEncoder

In [ ]:
# LabelEncoder object banaya (text ko numbers me convert karne ke liye)
le = LabelEncoder()

# 'name' column ki categories seekhta hai (fit)
# aur unhe numbers (0,1,2,...) me convert karta hai (transform)
le.fit_transform(df["name"])

array([4, 2, 1, 3, 0])

In [ ]:
# LabelEncoder object banaya (text ko numbers me convert karne ke liye)
le = LabelEncoder()

# 'name' column ko encode karke naya column 'en_name' me store kiya
# fit() → unique names seekhta hai
# transform() → unhe numbers (0,1,2,...) me convert karta hai
df["en_name"] = le.fit_transform(df["name"])

In [ ]:
df

     name  en_name
0  wscube        4
1     cow        2
2     cat        1
3     dog        3
4   black        0

In [ ]:
df = pd.read_csv(r"C:\Users\harsh\Downloads\archive (1)\uk_universities.csv")
df.head(3)

,University_name,Region,Founded_year,Motto,UK_rank,World_rank,CWUR_score,Minimum_IELTS_score,UG_average_fees_(in_pounds),PG_average_fees_(in_pounds),...,Student_satisfaction,Student_enrollment,Academic_staff,Control_type,Academic_Calender,Campus_setting,Estimated_cost_of_living_per_year_(in_pounds),Latitude,Longitude,Website
0,University of Cambridge,East of England,1209,"From here, light and sacred draughts",1,4,94.1,6.5,21750,23187,...,85.50%,"20,000-24,999","over-5,000",Public,Trimesters,Urban,12000,52.2054,0.1132,www.cam.ac.uk
1,University of Oxford,South East England,1096,The Lord is my light,2,2,93.3,6.5,21770,19888,...,86.50%,"25,000-29,999","over-5,000",Public,Trimesters,Urban,11500,51.7548,-1.2544,www.ox.ac.uk
2,University of St Andrews,Scotland,1413,Ever to excel,3,86,75.8,6.5,17040,15440,...,87.90%,"10,000-14,999","1,000-1,499",Public,Semesters,Suburban,12000,56.3417,-2.7943,www.st-andrews.ac.uk

In [ ]:
la = LabelEncoder()
la.fit(df["Region"])

LabelEncoder()

In [ ]:
la.transform(df["Region"])

array([ 1,  7,  6,  2,  0,  2,  3,  4,  2, 10,  8,  8, 11, 10,  8,  6,  9,
        4,  7,  7,  0, 11,  1,  6,  6, 11,  6,  3,  4,  2,  9,  7,  6,  9,
        5,  6,  1,  7,  7,  0,  0,  7,  8,  2,  9, 10,  6, 10,  2, 10,  1,
        2, 10,  7,  3, 11,  7,  8,  5,  4, 11,  4,  1,  7,  3, 11,  2,  2,
        2,  9,  7,  8,  2,  0,  4,  8, 11,  4,  4,  2, 11,  6,  6,  2,  2,
        2,  3,  1,  8,  7,  0,  7, 10,  8,  8, 10,  6,  7,  6,  2,  6,  9,
        1,  8, 11,  2,  2,  6,  3,  8,  4,  9,  7,  9, 10,  0, 11,  7,  2,
        1,  4,  7, 11, 10,  4,  2,  2,  1,  1,  9,  2])

In [ ]:
regions = df["Region"].unique()
print(regions)

['East of England' 'South East England' 'Scotland' 'London'
 'East Midlands' 'North East England' 'North West England' 'West Midlands'
 'South West England' 'Yorkshire and the Humber' 'Wales'
 'Northern Ireland']

# Ordinal Encoding

In [ ]:
# 👉 Jab categories ka order (ranking) hota hai
# 👉 tab unhe numbers me convert karte hain order ke hisaab se

# 🔍 Example:

# Data:
# Size → Small, Medium, Large

# Small < Medium < Large

# Encoding:
# Small  → 0  
# Medium → 1  
# Large  → 2

In [ ]:
# ❗ Difference (important)

#   Encoding	             Kab use kare
# LabelEncoder	      order matter nahi karta
# OneHotEncoder	      categories independent ho
# OrdinalEncoder	      order important ho

In [6]:
df = pd.DataFrame({"Size": ["s", "m", "l", "xl", "s", "m", "l", "s", "s", "l", "xl", "m"]})
df.head()

  Size
0    s
1    m
2    l
3   xl
4    s

In [11]:
ord_data = [["s", "m", "l", "xl"]]

In [12]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
oe = OrdinalEncoder(categories=ord_data)  
# ordered categories define karke encoder object banaya

oe.fit(df[["Size"]])  
# Size column ki categories ko learn (mapping banata hai) kar raha hai

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [49]:
oe.transform(df[["Size"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [3.],
       [1.]])

In [50]:
df["Size_en"] = oe.transform(df[["Size"]])
df

   Size  Size_en  size_en_map
0     s      0.0            5
1     m      1.0            6
2     l      2.0            7
3    xl      3.0            8
4     s      0.0            5
5     m      1.0            6
6     l      2.0            7
7     s      0.0            5
8     s      0.0            5
9     l      2.0            7
10   xl      3.0            8
11    m      1.0            6

In [51]:
ord_data1 = {"s":5, "m":6, "l":7, "xl":8}

In [52]:
df["size_en_map"] = df["Size"].map(ord_data1)

In [53]:
df

   Size  Size_en  size_en_map
0     s      0.0            5
1     m      1.0            6
2     l      2.0            7
3    xl      3.0            8
4     s      0.0            5
5     m      1.0            6
6     l      2.0            7
7     s      0.0            5
8     s      0.0            5
9     l      2.0            7
10   xl      3.0            8
11    m      1.0            6