# Handling Duplicate Data

In [1]:
import pandas as pd

In [2]:
data = {"name":["a","b","c","d","a","c"], "eng":[8,7,5,8,8,5], "hindi":[2,3,4,5,2,6]}

In [3]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      6

In [4]:
# df["duplicated"] = df.duplicated()  

# # jo col. duplicate hoga -> True ,  else -> False

In [5]:
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      6

In [6]:
df.drop_duplicates()   
# duplicate rows remove karta hai
# default: first occurrence ko rakhta hai
# original df change nahi hota (temporary output)

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [7]:
df.drop_duplicates(inplace=True)   # duplicate value (col. -> 4) ko dlt  [Original dataset ko change]

In [8]:
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [9]:
df.shape

(5, 3)

# Replace And Data Type Change

In [10]:
df = pd.read_csv(r"C:\Users\harsh\Downloads\archive\AI Job Market Dataset.csv")
df

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9
3,4,Business Analyst,Startup,Healthcare,Germany,Remote,Mid,9,Master,0,1,0,1,1,95775,3,2025,High,7
4,5,Data Scientist,MNC,Healthcare,Germany,Hybrid,Mid,5,Master,1,1,1,0,0,111873,12,2021,Low,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10340,10341,Data Engineer,Startup,Technology,USA,Onsite,Entry,2,PhD,1,0,1,0,1,76426,4,2023,Low,4
10341,10342,Data Analyst,Medium,Healthcare,Australia,Hybrid,Entry,10,Master,1,1,0,0,1,61233,9,2024,Medium,6
10342,10343,Machine Learning Engineer,Startup,Education,Germany,Hybrid,Entry,4,PhD,0,0,0,1,0,103681,3,2026,Low,4
10343,10344,Data Engineer,MNC,E-commerce,Canada,Hybrid,Mid,5,PhD,1,1,1,0,0,112895,12,2024,High,9
10344,10345,AI Engineer,Startup,Education,Australia,Onsite,Mid,12,PhD,0,1,1,1,1,159570,11,2022,High,3

In [11]:
df.head(3)

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10345 entries, 0 to 10344
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   job_id                10345 non-null  int64
 1   job_title             10345 non-null  object
 2   company_size          10345 non-null  object
 3   company_industry      10345 non-null  object
 4   country               10345 non-null  object
 5   remote_type           10345 non-null  object
 6   experience_level      10345 non-null  object
 7   years_experience      10345 non-null  int64
 8   education_level       10345 non-null  object
 9   skills_python         10345 non-null  int64
 10  skills_sql            10345 non-null  int64
 11  skills_ml             10345 non-null  int64
 12  skills_deep_learning  10345 non-null  int64
 13  skills_cloud          10345 non-null  int64
 14  salary                10345 non-null  int64
 15  job_posting_month     10345 non-null  int64
 16  job_posting_year      10345 non-null  int64
 17  hiring_urgency        10345 non-null  object
 18  job_openings          10345 non-null  int64
dtypes: int64(11), object(8)
memory usage: 1.5+ MB

In [13]:
df["country"].value_counts()
# Ye code count karta hai ki har country kitni baar aayi hai dataset me

country
Germany      1498
Singapore    1490
Canada       1488
UK           1485
India        1470
USA          1459
Australia    1455
Name: count, dtype: int64

In [14]:
df["education_level"].fillna(df["education_level"].mode()[0], inplace=True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_9100\4245959247.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["education_level"].fillna(df["education_level"].mode()[0], inplace=True)

In [15]:
df["years_experience"] = df["years_experience"].replace(0, 10)

In [16]:
df["years_experience"].astype("float64")
# Ye temporary conversion hai → df me save nahi hoga

0         2.0
1        10.0
2        14.0
3         9.0
4         5.0
         ...
10340     2.0
10341    10.0
10342     4.0
10343     5.0
10344    12.0
Name: years_experience, Length: 10345, dtype: float64

In [18]:
df["years_experience"] = df["years_experience"].astype("float64")
# Ab datatype permanently float me convert ho jayega

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10345 entries, 0 to 10344
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   job_id                10345 non-null  int64
 1   job_title             10345 non-null  object
 2   company_size          10345 non-null  object
 3   company_industry      10345 non-null  object
 4   country               10345 non-null  object
 5   remote_type           10345 non-null  object
 6   experience_level      10345 non-null  object
 7   years_experience      10345 non-null  float64
 8   education_level       10345 non-null  object
 9   skills_python         10345 non-null  int64
 10  skills_sql            10345 non-null  int64
 11  skills_ml             10345 non-null  int64
 12  skills_deep_learning  10345 non-null  int64
 13  skills_cloud          10345 non-null  int64
 14  salary                10345 non-null  int64
 15  job_posting_month     10345 non-null  int64
 16  job_posting_year      10345 non-null  int64
 17  hiring_urgency        10345 non-null  object
 18  job_openings          10345 non-null  int64
dtypes: float64(1), int64(10), object(8)
memory usage: 1.5+ MB