In [33]:
import pandas as pd
import numpy as np

In [34]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [35]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [36]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [37]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

# Working with Dates

In [38]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [39]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [40]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
54  2018-09-26        3196       29       1       2018
905 2018-08-22         133       16       2       2018
59  2019-10-25        4756        2      13       2019
280 2018-08-18        6716       16       2       2018
402 2018-11-05        4347       25     131       2018

### 2. Extract Month

In [41]:
date['date_month_no'] = date['date'].dt.month

date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
269 2019-03-21        6567       25       1       2019              3
637 2019-02-15         957       22       4       2019              2
132 2018-10-08        4152       28       1       2018             10
210 2018-10-13        3403        1      15       2018             10
740 2019-08-05         709       16     220       2019              8

In [42]:
date['date_month_name'] = date['date'].dt.month_name()

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
580,2018-09-29,5965,13,2,2018,9,September
681,2018-09-08,6483,28,2,2018,9,September
125,2019-03-13,5874,9,5,2019,3,March
778,2018-12-13,2235,16,14,2018,12,December
156,2019-04-25,568,8,25,2019,4,April

### 3. Extract Days

In [43]:
date['date_day'] = date['date'].dt.day

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
866,2019-11-27,1307,1,7,2019,11,November,27
597,2018-10-18,4846,1,1,2018,10,October,18
679,2019-11-11,4068,25,5,2019,11,November,11
663,2018-11-19,3761,16,1,2018,11,November,19
233,2019-08-17,2411,23,6,2019,8,August,17

#### day of week

In [44]:
date['date_dow'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
333,2019-10-31,1494,25,71,2019,10,October,31,3
85,2019-11-13,5288,18,7,2019,11,November,13,2
487,2019-04-18,6095,9,1,2019,4,April,18,3
122,2019-12-04,3076,18,8,2019,12,December,4,2
773,2019-11-23,1479,16,3,2019,11,November,23,5

####  day of week - name

In [45]:
date['date_dow_name'] = date['date'].dt.day_name()

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
229,2019-11-29,4047,16,5,2019,11,November,29,4,Friday
111,2019-10-17,3597,26,2,2019,10,October,17,3,Thursday
818,2018-11-06,6941,30,9,2018,11,November,6,1,Tuesday
100,2018-11-22,6343,22,191,2018,11,November,22,3,Thursday
910,2019-04-25,2504,2,2,2019,4,April,25,3,Thursday

#### is weekend?

In [46]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

#### Extract Quarter

In [48]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

#### Extract Semester

In [49]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

#### Extract Time elapsed between dates
(do dates ke beech kitna time (difference) gaya hai ya kitna duration hai, wo nikalna)

In [50]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 9, 16, 47, 53, 843024)

In [51]:
today - date['date']

0     2373 days 16:47:53.843024
1     2855 days 16:47:53.843024
2     2786 days 16:47:53.843024
3     2488 days 16:47:53.843024
4     2711 days 16:47:53.843024
                 ...
995   2801 days 16:47:53.843024
996   2742 days 16:47:53.843024
997   2590 days 16:47:53.843024
998   2655 days 16:47:53.843024
999   2429 days 16:47:53.843024
Name: date, Length: 1000, dtype: timedelta64[ns]

In [52]:
(today - date['date']).dt.days

0      2373
1      2855
2      2786
3      2488
4      2711
       ...
995    2801
996    2742
997    2590
998    2655
999    2429
Name: date, Length: 1000, dtype: int64

In [54]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [56]:
# Convert the 'date' column from string/object format to datetime format
# This allows us to perform time-based operations like extracting year, month, day,
# and calculating time differences between dates
time['date'] = pd.to_datetime(time['date'])

In [57]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [58]:
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

# Extract Time part

In [59]:
time['time'] = time['date'].dt.time

In [60]:
time.head()

,date,msg,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23:11:00

### Time difference

In [61]:
today - date['date']

0     2373 days 16:47:53.843024
1     2855 days 16:47:53.843024
2     2786 days 16:47:53.843024
3     2488 days 16:47:53.843024
4     2711 days 16:47:53.843024
                 ...
995   2801 days 16:47:53.843024
996   2742 days 16:47:53.843024
997   2590 days 16:47:53.843024
998   2655 days 16:47:53.843024
999   2429 days 16:47:53.843024
Name: date, Length: 1000, dtype: timedelta64[ns]

#### in Seconds

In [64]:
# Calculate time difference between 'today' and each date in the column
# (today - time['date']) gives a timedelta (difference in days/hours/etc.)

# Convert that timedelta into seconds by dividing with 1 second unit
# np.timedelta64(1, 's') means 1 second, so result becomes total seconds difference

(today - time['date']) / np.timedelta64(1, 's')

0      3.939551e+08
1      3.822089e+08
2      4.241968e+08
3      3.638890e+08
4      3.981946e+08
           ...
995    4.491647e+08
996    3.905048e+08
997    4.306795e+08
998    4.407020e+08
999    3.778034e+08
Name: date, Length: 1000, dtype: float64

#### in minutes

In [65]:
(today - time['date'])/np.timedelta64(1,'m')

0      6.565918e+06
1      6.370148e+06
2      7.069947e+06
3      6.064817e+06
4      6.636577e+06
           ...
995    7.486078e+06
996    6.508414e+06
997    7.177991e+06
998    7.345034e+06
999    6.296723e+06
Name: date, Length: 1000, dtype: float64

#### in hours

In [66]:
(today - time['date'])/np.timedelta64(1,'h')

0      109431.964956
1      106169.131623
2      117832.448290
3      101080.281623
4      110609.614956
           ...
995    124767.964956
996    108473.564956
997    119633.181623
998    122417.231623
999    104945.381623
Name: date, Length: 1000, dtype: float64