# Preprocessing

### Categorical Data
##### Categorical data preprocessing is the process of converting non-numeric categories into numerical values so that machine learning algorithms can process them. Common techniques include Label Encoding and One-Hot Encoding.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create dataset
df = pd.DataFrame({
    "Car": [
        "Toyota", "Mitsubishi", "Skoda", "Fiat",
        "Mini", "VW", "Skoda", "Mercedes",
        "Ford", "Audi", "Hyundai", "Suzuki"
    ],

    "Model": [
        "Aygo", "Space Star", "Citigo", "500",
        "Cooper", "Up!", "Fabia", "A-Class",
        "Fiesta", "A1", "I20", "Swift"
    ],

    "Volume": [
        1000, 1200, 1000, 900,
        1500, 1000, 1400, 1500,
        1500, 1600, 1100, 1300
    ],

    "Weight": [
        790, 1160, 929, 865,
        1140, 929, 1109, 1365,
        1112, 1150, 980, 990
    ],

    "CO2": [
        99, 95, 95, 90,
        105, 105, 90, 92,
        98, 99, 99, 101
    ]
})

print(df)

           Car       Model  Volume  Weight  CO2
0       Toyota        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101

##### Methods to Convert Categorical Data

# One Hot Encoding

In [3]:
df_encoded = pd.get_dummies(
    df,
    columns = ['Car', 'Model'],
    dtype = int
)

df_encoded

,Volume,Weight,CO2,Car_Audi,Car_Fiat,Car_Ford,Car_Hyundai,Car_Mercedes,Car_Mini,Car_Mitsubishi,...,Model_A1,Model_Aygo,Model_Citigo,Model_Cooper,Model_Fabia,Model_Fiesta,Model_I20,Model_Space Star,Model_Swift,Model_Up!
0,1000,790,99,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1200,1160,95,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,1000,929,95,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,900,865,90,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1500,1140,105,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
5,1000,929,105,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,1400,1109,90,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,1500,1365,92,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1500,1112,98,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9,1600,1150,99,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
10,1100,980,99,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11,1300,990,101,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [4]:
print(df_encoded.columns)

Index(['Volume', 'Weight', 'CO2', 'Car_Audi', 'Car_Fiat', 'Car_Ford',
       'Car_Hyundai', 'Car_Mercedes', 'Car_Mini', 'Car_Mitsubishi',
       'Car_Skoda', 'Car_Suzuki', 'Car_Toyota', 'Car_VW', 'Model_500',
       'Model_A-Class', 'Model_A1', 'Model_Aygo', 'Model_Citigo',
       'Model_Cooper', 'Model_Fabia', 'Model_Fiesta', 'Model_I20',
       'Model_Space Star', 'Model_Swift', 'Model_Up!'],
      dtype='object')

In [5]:
print(df.shape)

(12, 5)

In [6]:
print(df_encoded.shape)

(12, 26)

In [7]:
X = df_encoded.drop(
    'CO2',
    axis = 1
)

y = df_encoded['CO2']

# LabelEncoder

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
la = LabelEncoder()

In [13]:
# Convert the categorical values in the
# 'Car' column into numerical labels

df['Car'] = la.fit_transform(df['Car'])

df['Car']

0      9
1      6
2      7
3      1
4      5
5     10
6      7
7      4
8      2
9      0
10     3
11     8
Name: Car, dtype: int64

In [17]:
# Convert the categorical values in the
# 'Model' column into numerical labels

df['Model'] = la.fit_transform(df['Model'])

df['Model']

0      3
1      9
2      4
3      0
4      5
5     11
6      6
7      1
8      7
9      2
10     8
11    10
Name: Model, dtype: int64

In [18]:
df

    Car  Model  Volume  Weight  CO2
0     9      3    1000     790   99
1     6      9    1200    1160   95
2     7      4    1000     929   95
3     1      0     900     865   90
4     5      5    1500    1140  105
5    10     11    1000     929  105
6     7      6    1400    1109   90
7     4      1    1500    1365   92
8     2      7    1500    1112   98
9     0      2    1600    1150   99
10    3      8    1100     980   99
11    8     10    1300     990  101

In [19]:
print(la.classes_)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [23]:
print(len(la.classes_))

12

In [24]:
print(df['Car'].unique())

[ 9  6  7  1  5 10  4  2  0  3  8]